### ISSUE TITLE
Nintendo N64 bezel is upside down

### ISSUE THREAD

**Issue by BackSpace54** [soqueroeu/Soqueroeu-TV-Backgrounds_V2.0#1]
Hi,
could you check the N64 bezel?
For me it's upside down ;-)
RA 1.14 + Mega Bezel 1.8.1
Thanks.

**Comment by soqueroeu** [comment]
Hi!

I'm sorry for answering so late.
I invite you to expose your doubts in the Libretro forum itself. There is a more active community about shaders there and certainly your doubts will be answered more quickly.

https://forums.libretro.com/t/soqueroeu-mega-bezel-tv-backgrounds/34301

Thanks

**Comment by soqueroeu** [comment]
In any case, this problem is caused by the chosen Core. Some of them may have strange behavior with the screen and this can be solved by changing the flip options, in shader parameters. Go to [FLIP & ROTATE] sub menu and change Flip Viewport Vertical parameter.

**Comment by BackSpace54** [comment]
Hi,
ok will go to the libretro forum.
Thanks.
